### ISSUE TITLE
schema definitions should be split into separate package

### ISSUE THREAD

**Issue by kleinschmidt** [beacon-biosignals/OndaEDF.jl#50]
In order for the schemas defined here to be used in any downstream package, they have to take OndaEDF as a depedendency, even if they just want to register that say a `"ondaedf.file-plan@1"` table is part of a dataset, or just load these tables to later analysis.  OndaEDF is pretty hefty dependency for these "dataset packages" which only track persistent identifiers of where tables with different schemas can be found.  We can fix this by splitting out the schema definitions in this package into an OndaEDFSchemas.jl package that's a "light" dependency.

**Comment by ericphanson** [comment]
Yeah, I think if you want to be able to make a PR that updates two packages simulatenously/atomically, then a subpackage is good. I think schemas are a great example of that. SnoopCompile / SnoopCompileCore (https://github.com/timholy/SnoopCompile.jl) is another example of this, or Makie + it's backends.

**Comment by kleinschmidt** [comment]
done with #51 and #53
